### PR TITLE
fix offset when using last and before together

### PR DESCRIPTION
**Pull request by tavipoldma**
Thanks for great packages, tiny fix is needed.
There is incorrect offset when using last and before together.

Right now:
20 items in the database, ids 0-19
{ last: 5 } returns 5 nodes with ids 15-19 and startCursor
{ last: 5, before: 'STARTCURSOR' } returns incorrectly 2 nodes, ids 13-14

After this pull request:
{ last: 5, before: 'STARTCURSOR' } returns correctly 5 nodes with ids 10-14

### CODE REVIEW

**Comment by lobodart** [comment]
Hi @tavipoldma! Thanks for the fix. I'll have a look at it this week!

**Comment by tavipoldma** [comment]
Hey @lobodart 
This probably needs more than one :coffee: to validate, just checking if you had time to take a look?

**Comment by lobodart** [comment]
@tavipoldma Sorry, didn't have time this week but I will have a look tonight or tomorrow ☺️

**Comment by lobodart** [comment]
Hi @tavipoldma! I just checked and was able to reproduce the issue. Your edit seems to fix the problem but I am not a fan of doing one more database query. I am going to merge your PR as a quick fix for now and I will improve the code in a future version (I'm currently working on a new version without `skip` and using Typescript). Thanks again for having pointed out this issue :)

**Pull request merged**
